/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookfutsal;

import javax.swing.*;

/**
 *
 * @author ROG
 */
public class FormBooking extends javax.swing.JFrame {

    double jam,lama, bayar;
    String nama;
    int tarif;
    /**
     * Creates new form FormBooking
     */
    public FormBooking() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtJam = new javax.swing.JTextField();
        txtLama = new javax.swing.JTextField();
        btnHasil = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        hasilNama = new javax.swing.JTextField();
        hasilJam = new javax.swing.JTextField();
        hasilHarga = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        totalBayar = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nike Futsal Booking ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(620, 20, 230, 40);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel2.setText("List Harga");

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel3.setText("1.06:00-12:00 ---------->Rp50.000/Jam");

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel4.setText("2.12:00-16:00 ---------->Rp65.000/jam");

        jLabel5.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel5.setText("3.16:00-24:00 ---------->Rp110.000/jam");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel2)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(510, 110, 440, 140);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Burn Your Spirit Up !!");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(660, 60, 130, 40);

        jLabel7.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel7.setText("Nama Pelanggan   :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(510, 290, 280, 50);

        jLabel8.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel8.setText("Jam Booking(1-3)  :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(510, 360, 290, 50);

        jLabel9.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel9.setText("Lama Booking(1-999 jam) :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(430, 430, 320, 50);

        txtNama.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        getContentPane().add(txtNama);
        txtNama.setBounds(770, 300, 180, 50);

        txtJam.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        txtJam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJamActionPerformed(evt);
            }
        });
        getContentPane().add(txtJam);
        txtJam.setBounds(770, 370, 180, 50);

        txtLama.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        txtLama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLamaActionPerformed(evt);
            }
        });
        getContentPane().add(txtLama);
        txtLama.setBounds(770, 440, 180, 50);

        btnHasil.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        btnHasil.setText("Hasil");
        btnHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHasilActionPerformed(evt);
            }
        });
        getContentPane().add(btnHasil);
        btnHasil.setBounds(570, 510, 80, 31);

        btnHapus.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapus);
        btnHapus.setBounds(770, 510, 80, 31);

        jLabel10.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel10.setText("Nama Pelanggan     :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(500, 550, 250, 50);

        jLabel11.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel11.setText(" Jam booking            :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(490, 610, 250, 50);

        jLabel12.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel12.setText(" Harga book              :");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(490, 670, 250, 50);

        hasilNama.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        hasilNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilNamaActionPerformed(evt);
            }
        });
        getContentPane().add(hasilNama);
        hasilNama.setBounds(770, 560, 180, 50);

        hasilJam.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        getContentPane().add(hasilJam);
        hasilJam.setBounds(770, 620, 180, 50);

        hasilHarga.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        hasilHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilHargaActionPerformed(evt);
            }
        });
        getContentPane().add(hasilHarga);
        hasilHarga.setBounds(770, 680, 180, 50);

        jLabel13.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel13.setText("Total Bayar              :");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(500, 740, 240, 40);

        totalBayar.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        totalBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalBayarActionPerformed(evt);
            }
        });
        getContentPane().add(totalBayar);
        totalBayar.setBounds(770, 740, 180, 50);

        jLabel14.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookfutsal/Hijau Abstrak Lomba Futsal Pamflet.png"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(-270, 0, 2100, 920);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void txtJamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJamActionPerformed

    private void txtLamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLamaActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        txtNama.setText("");
        txtJam.setText("");
        txtLama.setText("");
        hasilNama.setText("");
        hasilHarga.setText("");
        hasilJam.setText("");
        totalBayar.setText("");
        
    }//GEN-LAST:event_btnHapusActionPerformed

    private void hasilNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilNamaActionPerformed

    private void hasilHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilHargaActionPerformed

    private void totalBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalBayarActionPerformed

    private void btnHasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHasilActionPerformed
nama = String.valueOf(txtNama.getText());
jam = Float.parseFloat(txtJam.getText());
lama = Float.parseFloat(txtLama.getText());
hasilNama.setText(""+nama);

if(nama!=null){
    if(jam == 1){   
        hasilJam.setText("06:00-12:00");
        hasilHarga.setText("Rp.50000/jam");
        tarif = (int) (lama*50000);
        totalBayar.setText("Rp."+tarif);    
    }else if (jam == 2){   
        hasilJam.setText("12:00-16:00");
        hasilHarga.setText("Rp.65000/jam");
        tarif = (int) (lama*65000);
        totalBayar.setText("Rp."+tarif);   
    }else if (jam == 3){

        hasilJam.setText("16:00-24:00");
        hasilHarga.setText("Rp.110000/jam");
        tarif = (int) (lama*110000);
        totalBayar.setText("Rp."+tarif);      
    }else {
         JOptionPane.showMessageDialog(null,"Hanya dapat memilih jam booking 1-3");
        }  
    }
 
    }//GEN-LAST:event_btnHasilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHasil;
    private javax.swing.JTextField hasilHarga;
    private javax.swing.JTextField hasilJam;
    private javax.swing.JTextField hasilNama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField totalBayar;
    private javax.swing.JTextField txtJam;
    private javax.swing.JTextField txtLama;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
}
